from enum import Enum


class ErrorCode(str, Enum):
    FOOTBALL_PROVIDER_UNAVAILABLE = "FOOTBALL_PROVIDER_UNAVAILABLE"
    FOOTBALL_PROVIDER_RATE_LIMITED = "FOOTBALL_PROVIDER_RATE_LIMITED"
    FOOTBALL_PROVIDER_INVALID_RESPONSE = "FOOTBALL_PROVIDER_INVALID_RESPONSE"
    FOOTBALL_PROVIDER_TIMEOUT = "FOOTBALL_PROVIDER_TIMEOUT"

    MATCH_NOT_FOUND = "MATCH_NOT_FOUND"

    STREAM_UNAVAILABLE = "STREAM_UNAVAILABLE"
    STREAM_UNAUTHORIZED = "STREAM_UNAUTHORIZED"
    STREAM_PROVIDER_ERROR = "STREAM_PROVIDER_ERROR"

    AI_PROVIDER_UNAVAILABLE = "AI_PROVIDER_UNAVAILABLE"
    AI_PROVIDER_RATE_LIMITED = "AI_PROVIDER_RATE_LIMITED"
    AI_GENERATION_FAILED = "AI_GENERATION_FAILED"
    AI_VALIDATION_FAILED = "AI_VALIDATION_FAILED"
    AI_OUTPUT_MALFORMED = "AI_OUTPUT_MALFORMED"

    DATABASE_ERROR = "DATABASE_ERROR"
    DATABASE_TIMEOUT = "DATABASE_TIMEOUT"

    INTERNAL_ERROR = "INTERNAL_ERROR"
    INVALID_REQUEST = "INVALID_REQUEST"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"


ERROR_STATUS_MAP: dict[ErrorCode, int] = {
    ErrorCode.FOOTBALL_PROVIDER_UNAVAILABLE: 503,
    ErrorCode.FOOTBALL_PROVIDER_RATE_LIMITED: 429,
    ErrorCode.FOOTBALL_PROVIDER_INVALID_RESPONSE: 502,
    ErrorCode.FOOTBALL_PROVIDER_TIMEOUT: 504,
    ErrorCode.MATCH_NOT_FOUND: 404,
    ErrorCode.STREAM_UNAVAILABLE: 200,
    ErrorCode.STREAM_UNAUTHORIZED: 403,
    ErrorCode.STREAM_PROVIDER_ERROR: 502,
    ErrorCode.AI_PROVIDER_UNAVAILABLE: 503,
    ErrorCode.AI_PROVIDER_RATE_LIMITED: 429,
    ErrorCode.AI_GENERATION_FAILED: 503,
    ErrorCode.AI_VALIDATION_FAILED: 200,
    ErrorCode.AI_OUTPUT_MALFORMED: 502,
    ErrorCode.DATABASE_ERROR: 500,
    ErrorCode.DATABASE_TIMEOUT: 504,
    ErrorCode.INTERNAL_ERROR: 500,
    ErrorCode.INVALID_REQUEST: 400,
    ErrorCode.SERVICE_UNAVAILABLE: 503,
}
