"""initial schema

Revision ID: 70ce5cafd5a1
Revises: 
Create Date: 2026-09-16 01:59:27.998540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70ce5cafd5a1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('season', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_name', 'external_id', name='uq_league_provider_external')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=10), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_name', 'external_id', name='uq_team_provider_external')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('added_time', sa.Integer(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('ht_home_score', sa.Integer(), nullable=True),
    sa.Column('ht_away_score', sa.Integer(), nullable=True),
    sa.Column('match_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('venue', sa.String(length=255), nullable=True),
    sa.Column('referee', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_name', 'external_id', name='uq_match_provider_external')
    )
    op.create_index('idx_matches_date', 'matches', ['match_date'], unique=False)
    op.create_index('idx_matches_league', 'matches', ['league_id'], unique=False)
    op.create_index('idx_matches_status', 'matches', ['status'], unique=False)
    op.create_table('ai_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('analysis_type', sa.String(length=50), nullable=False),
    sa.Column('context_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('interpretation', sa.Text(), nullable=False),
    sa.Column('key_insights', sa.Text(), nullable=True),
    sa.Column('reference_validation_rate', sa.Integer(), nullable=True),
    sa.Column('validation_label', sa.String(length=20), nullable=True),
    sa.Column('data_references', sa.Text(), nullable=True),
    sa.Column('validation_result', sa.String(length=20), nullable=True),
    sa.Column('ai_provider', sa.String(length=50), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_analysis_match', 'ai_analysis', ['match_id', 'analysis_type'], unique=False)
    op.create_table('match_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('external_event_id', sa.String(length=100), nullable=True),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('added_time', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('player_name', sa.String(length=255), nullable=True),
    sa.Column('assist_player', sa.String(length=255), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_match', 'match_events', ['match_id'], unique=False)
    op.create_table('match_statistics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('stat_type', sa.String(length=50), nullable=False),
    sa.Column('home_value', sa.String(length=50), nullable=True),
    sa.Column('away_value', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'stat_type', name='uq_match_stat_type')
    )
    op.create_table('stream_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('stream_url', sa.Text(), nullable=False),
    sa.Column('embed_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('authorization_status', sa.String(length=20), nullable=False),
    sa.Column('legal_basis', sa.Text(), nullable=False),
    sa.Column('authorized_by', sa.String(length=255), nullable=True),
    sa.Column('authorized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quality', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stream_match', 'stream_sources', ['match_id', 'is_active', 'authorization_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_stream_match', table_name='stream_sources')
    op.drop_table('stream_sources')
    op.drop_table('match_statistics')
    op.drop_index('idx_events_match', table_name='match_events')
    op.drop_table('match_events')
    op.drop_index('idx_ai_analysis_match', table_name='ai_analysis')
    op.drop_table('ai_analysis')
    op.drop_index('idx_matches_status', table_name='matches')
    op.drop_index('idx_matches_league', table_name='matches')
    op.drop_index('idx_matches_date', table_name='matches')
    op.drop_table('matches')
    op.drop_table('teams')
    op.drop_table('leagues')
    # ### end Alembic commands ###
